version: '3'

services:
  ezcoinsapi:
    image: node:14.17.5-alpine3.14
    container_name: ezcoinsapi
    command: sh -c "cd /usr/src/api && yarn run build && node dist/server.js"
    networks:
      - node-network
    volumes:
      - .:/usr/src/api
    ports:
      - 3003:3003
    tty: true

networks:
  node-network:
    driver: bridge
